email:
  development:
    address: smtp.gmail.com
    port: 587
    domain: gmail.com
    user_name: localemail2@gmail.com
    password: LocalEmail
  production:
    address:
    port:
    domain:
    user_name:
    password:

devise:
  development:
    mailer_sender: localemail2@gmail.com
  production:
    mailer_sender: 

airbrake:
  production:
    api_key:
