email:
  development:
    address: smtp.gmail.com
    port: 587
    domain: gmail.com
    user_name: 
    password: 
  production:
    address:
    port:
    domain:
    user_name:
    password:

devise:
  development:
    mailer_sender: 
  production:
    mailer_sender: 

airbrake:
  production:
    api_key:
